### PR TITLE
Refactor: Merge mwc into bmq

### PR DESCRIPTION
**Pull request by hallfox**
MWC or "MiddleWare Core" was a package group developed to support a myriad of applications at Bloomberg. It's been useful to share common middleware components between similar technologies, but doesn't make much sense to support as its own open source library. Moving forward we are merging it into the BMQ package group to better maintain it for the BlazingMQ project.

### CODE REVIEW

**Comment by pniedzielski** [comment]
@hallfox some failing clang-format checks...probably (though not obviously, to me) related to your rename.  Probably best to pay this debt down now rather than merge with failing CI.

**Comment by pniedzielski** [comment]
Tested this patch doxygen, thankfully nothing new was built.  This should make it easier to build docs for former-MWC, though.

**Comment by pniedzielski** [comment]
Still see three references to mwc:

```
.github/workflows/build.yaml
166:          ctest -E mwcsys_executil.t --output-on-failure
.github/workflows/sanitizers/build_sanitizer.sh
286:CMD+="./run-env.sh ctest -E mwcsys_executil.t --output-on-failure"
CMakeLists.txt
117:  set(BMQ_TARGET_MWC_NEEDED            YES)
```

**Review by pniedzielski — CHANGES_REQUESTED** [review]
I still see three references to mwc in the codebase (see comment), and one of them is for a unit test that is failing in CI.

  - Doxygen builds fine (does not run on former mwc components)
  - Builds fine
  - Unit test fails

**Review by pniedzielski — COMMENTED** [review]
Is

```
CMakeLists.txt
117:  set(BMQ_TARGET_MWC_NEEDED            YES)
```

still needed?  I see the variable assignment was removed at (former) line 140 in the PR.

**Review by chrisbeard — APPROVED** [review]
lgtm, maybe @pniedzielski can give a second sanity check here

**Review by pniedzielski — APPROVED** [review]
let's merge 💯

**Pull request merged**
