### PR TITLE
Convert package-level and component-level documentation into form Doxygen can understand

### PR DESCRIPTION
**Pull request by pniedzielski**
**Issue number of the reported bug or feature request: #118**

**Describe your changes**
The changes in this PR convert our _package-level_ and _component-level_ documentation into _directory_ and _file_ documentation, respectively, so that Doxygen is able to understand them.  Please see the messages on each commit for further details.

Note that I have not included the _built_ documentation files, which live in `docs/docs/apidocs/cpp_apidocs/`.  We may want to keep these on a separate branch (`gh-pages`?), and the current output of Doxygen is still not optimal (see **Future changes** below for details), so I will not modify these in this PR.

**Testing performed**
Testing the documentation build by running `doxygen` manually from the root of the repository.  Using Doxygen version 1.9.8, the only warnings left are because we use the project's `README.md` as our API docs' starting point.  This should be changed.

**Future changes**
A few more changes need to be made to the documentation so we can automatically generate it on release:

  1. **Catch conversion errors from BDE-style documentation to Doxygen documentation.** As noted in the linked issue, there are some places which confused the automated conversion tool, leaving us with old-style BDE formatting that Doxygen cannot understand.  These should be changed.
  2. **Add a real `\mainpage`, which links to each of the packages for easier discoverability.**  This will also fix the remaining Doxygen warnings.
  3. **Teach CMake to find and run Doxygen.** This will let us call the equivalent of `make doc` to generate documentation, which we can do in our CI.  This will let us catch documentation errors in CI and ultimately publish the documentation automatically on releases.
  4. (As a nice-to-have,) **Convert BDE class member grouping to a form Doxygen understands.** Doxygen provides the ability to divide class members into arbitrary groups with names.  If this change is not too intrusive, we can consider doing this to make our API docs easier to understand.

### CODE REVIEW

**Comment by hallfox** [comment]
Looks pretty good! I'm happy with the rendered output, even though we've lost the component level breakdown in packages. A few things I'm noticing:

1. Package level documentation appears to be rendering as README links in the related pages section without any of the contents in the README. Is this expected? (Or am I seeing something weird?)
2. Several "impl" classes are visible in the documentation that weren't visible in the previous one. My guess is there was some rule in bdedox that was excluding them by the nature of that name, or some option we had enabled that was removed that I can't see in this PR. Is it likely we'll be able to hide these again? Or should we find other ways to mark them as internal only? Seems like doxygen's `\internal` command might help us here.

**Comment by pniedzielski** [comment]
> I'm happy with the rendered output, even though we've lost the component level breakdown in packages.

Yeah, IIRC component levelization was not part of the OSS release (see https://github.com/bloomberg/blazingmq/commit/ed9fa8e72e0c84689f4a5fc94a0ea6316e49b6ac for the only other commit to these READMEs), but it would be nice to add it back in.  I believe the currently published levelization is incomplete, but I would need to check again.

> 1. Package level documentation appears to be rendering as README links in the related pages section without any of the contents in the README. Is this expected? (Or am I seeing something weird?)

This is "expected", but I haven't found a good way around it.  See https://github.com/doxygen/doxygen/issues/9437, it's a known issue.  Doesn't help us much though.

> 2. Several "impl" classes are visible in the documentation that weren't visible in the previous one. My guess is there was some rule in bdedox that was excluding them by the nature of that name, or some option we had enabled that was removed that I can't see in this PR. Is it likely we'll be able to hide these again? Or should we find other ways to mark them as internal only? Seems like doxygen's `\internal` command might help us here.

`\internal` is a good solution here.  Since in BDE-style docs, the publically-usable symbols are listed in component-level documentation, it may be that `bdedox` only generates documentation for those symbols listed in the component-level documentation.  Either way, we removed that list in this PR intentionally, so `\internal` is a good idea.

I don't have a good solution to the first issue (I was thinking of it lumped together with our `\mainpage` being a broken version of the project README as a "later" problem...), but I'll do the latter in this PR.

**Comment by hallfox** [comment]
> I don't have a good solution to the first issue (I was thinking of it lumped together with our \mainpage being a broken version of the project README as a "later" problem...), but I'll do the latter in this PR.

I'm okay with this for now.

I think we should keep hiding the internal components.

**Comment by pniedzielski** [comment]
@hallfox Rebased onto `main`, but included two additional commits that address internal components being shown in the generated documentation.

**Review by hallfox — APPROVED** [review]
lgtm

**Pull request merged**
