### PR TITLE
Docs: add blog post about performance

### PR DESCRIPTION
**Pull request by 678098**

### CODE REVIEW

**Review by chrisbeard — APPROVED** [review]
nice work @678098 , let's 🚢  it

**Review by chrisbeard — CHANGES_REQUESTED** [review]
Do we want to update all filenames to match the title?

**Comment by chrisbeard** [comment]
I guess the main one is the `.md` file, as that affects the URL

**Review by pniedzielski — APPROVED** [review]
💯

**Review by chrisbeard — APPROVED** [review]
👍

**Pull request merged**
